### ISSUE TITLE
unable to find dependency soundmanager2

### ISSUE THREAD

**Issue by jonbonraki** [davidtran/angular2-soundcloud#1]
![image](https://cloud.githubusercontent.com/assets/8699057/13031837/87090c6a-d28f-11e5-85d7-51679997c5ad.png)
- 1. Refer the screenshot 
- 2.unable to find soundmanager2 script from node nodules
- 3. i guess the package json has a missing dependency for the project

**Comment by davidtran** [comment]
Forgot to add soundmanager to npm package. I have added it.

**Comment by jonbonraki** [comment]
thanks

**Comment by jonbonraki** [comment]
i still dont see the soundmanager 2,same issue, in updated package.json only change isee is zone.js being removed

https://github.com/davidtran/angular2-soundcloud/commit/dbf09b63a644f40e43072917873ff42c1d1f14f3

let me know if i missing something

**Comment by jonbonraki** [comment]
i see it now thanks for adding
